metrics:
  enabled: true
container:
  pool:
    cpus: 2
    memory: 1024
api:
  port: 1323
cloud:
  server:
    url: http://192.168.1.27:1325
scheduler:
  #policy: edgecloud
  policy: customCloudOffload
registry:
  udp:
    port: 9876